version: '3.8'

volumes:
  postgres-data:
    null

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOSTNAME=db
      - USER_AGENT=[USER AGENT HERE]
      - UNIQUE_QUEUE_ID=[QUEUE ID HERE]
      - BOT_TOKEN=[TOKEN HERE]
    network_mode: service:db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    ports:
      - 5432:5432