version: '3.8'

volumes:
  postgres-data:
    null
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.18-bullseye
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    ports:
      - 5432:5432
